[tool.poetry]
name = "kaa_mqtt_client"
version = "0.1.0"
description = "This library implements Kaa MQTT client"
authors = ["Oleksandr Burdeinyi <aburdeinyi@kaaiot.io>", "Viktor Kazanin <vkazanin@kaaiot.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
paho-mqtt = "^1.5.1"
PyYAML = "^6.0"
  
[tool.poetry.dev-dependencies]
pytest = "^8.3.3"
pytest-cov = "^6.0.0"
pytest-benchmark = "^5.1.0"
codecov = "^2.1.13"
twine = "^5.1.1"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
